rancher:
  replicas: 1

  hostname: rancher.tom.lan

  privateCA: false

  bootstrapPassword: password

  ingress:
    enabled: true

    extraAnnotations:
      cert-manager.io/cluster-issuer: ca

    tls:
      source: rancher
