rancher:
  replicas: 1

  hostname: rancher.tom.lan

  # privateCA: false
  privateCA: true

  bootstrapPassword: password

  ingress:
    enabled: true

    extraAnnotations:
      cert-manager.io/cluster-issuer: ca

    tls:
      # source: rancher
      source: secret
