rancher:
  replicas: 1

  hostname: rancher.tom.lan

  privateCA: false

  bootstrapPassword: password

  ingress:
    enabled: true

    extraAnnotations:
      cert-manager.io/issuer: step-issuer
      cert-manager.io/issuer-kind: StepClusterIssuer
      cert-manager.io/issuer-group: certmanager.step.sm

    tls:
      source: rancher