apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-authentik-outpost-ingress
spec:
  ingressClassName: ingress-nginx
  rules:
  - host: cyber-chef.k3s.lan
    http:
      paths:
      - path: /outpost.goauthentik.io
        pathType: Prefix
        backend:
          service:
            name: ak-outpost-authentik-embedded-outpost
            port:
              name: http