postgresql:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 14.2.0-debian-10-r58
    pullPolicy: IfNotPresent

  auth:
    enablePostgresUser: true
    postgresPassword: postgres

    username: user
    password: password

    database: db
  
  architecture: standalone

  tls:
    enabled: false

  metrics:
    enabled: true