apiVersion: v1
kind: Service
metadata:
  name: {{- printf "%s-%s" .Release.Name .Chart.Name }}-service
  labels:
    app: {{- printf "%s-%s" .Release.Name .Chart.Name }}
    chart: {{- printf "%s-%s" .Chart.Name .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{- printf "%s-%s" .Release.Name .Chart.Name }}
    release: {{ .Release.Name }}