prometheus:
  server:
    replicaCount: 1
    image:
      tag: v2.34.0
    service:
      type: ClusterIP
      servicePort: 80
    global:
      scrape_interval: 30s
      scrape_timeout: 5s
    ingress:
      enabled: true
      pathType: Prefix
      path: /
      hosts:
        - prometheus.k3s.lan
      annotations:
        nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.default.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/auth-signin: https://prometheus.k3s.lan/outpost.goauthentik.io/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
  serverFiles:
    prometheus.yml:
      scrape_configs:
      - job_name: skyrouter
        metrics_path: /
        static_configs:
        - targets:
          - skyrouter-exporter:80