prometheus:
  server:
    replicaCount: 1
    image:
      tag: v2.34.0
    service:
      type: ClusterIP
      servicePort: 80
    global:
      scrape_interval: 30s
      scrape_timeout: 5s
    ingress:
      enabled: true
      pathType: Prefix
      path: /(.*)
      hosts:
        - prometheus.k3s.lan
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
  serverFiles:
    prometheus.yml:
      scrape_configs:
      - job_name: skyrouter
        metrics_path: /
        static_configs:
        - targets:
          - skyrouter-exporter:80