prometheus:
  server:
    replicaCount: 1
    image:
      tag: v2.34.0
    service:
      type: NodePort
      servicePort: 8080
    global:
      scrape_interval: 30s
      scrape_timeout: 5s
  serverFiles:
    prometheus.yml:
      scrape_configs:
      - job_name: skyrouter
        metrics_path: /
        static_configs:
        - targets:
          - skyrouter-exporter:8080