prometheus:
  server:
    replicaCount: 1
    image:
      tag: v2.34.0
    service:
      type: ClusterIP
      servicePort: 80
    global:
      scrape_interval: 30s
      scrape_timeout: 5s
    ingress:
      enabled: true
      pathType: Prefix
      path: /prometheus/(.*)
      hosts:
        - k3s-server
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
    extraFlags:
      - web.route-prefix=/
      - web.external-url=/prometheus/
  serverFiles:
    prometheus.yml:
      scrape_configs:
      - job_name: skyrouter
        metrics_path: /
        static_configs:
        - targets:
          - skyrouter-exporter:80