grafana:
  replicaCount: 1

  image:
    tag: 8.3.4-debian-10-r0
  
  admin:
    password: password

  persistence:
    enabled: false

  metrics:
    enabled: false

  config:
    useGrafanaIniFile: true
    grafanaIniConfigMap: grafana-config

  dashboardsConfigMaps:
    - grafana-dashboard-skyrouter

  ingress:
    enabled: true
    pathType: Prefix
    path: /grafana/(.*)
    hostname: k3s-server
    ingressClassName: ingress-nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1