grafana:
  replicaCount: 1

  image:
    tag: 8.3.4-debian-10-r0

  service:
    type: ClusterIP
    ports:
      grafana: 80
  
  admin:
    password: password

  persistence:
    enabled: false

  metrics:
    enabled: false

  config:
    useGrafanaIniFile: true
    grafanaIniConfigMap: grafana-config

  dashboardsProvider:
    enabled: true
  
  datasources:
    secretName: grafana-datasources

  dashboardsConfigMaps:
    - configMapName: grafana-dashboard-skyrouter
      fileName: dashboard-skyrouter.json

  ingress:
    enabled: true
    pathType: Prefix
    path: /(.*)
    hostname: grafana.k3s.lan
    ingressClassName: ingress-nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1