grafana:
  replicaCount: 1

  image:
    tag: 8.3.4-debian-10-r0
  
  admin:
    password: password

  persistence:
    enabled: false

  metrics:
    enabled: false

  ingress:
    enabled: true
    pathType: Prefix
    path: /grafana/(.*)
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    # ingressClassName: ingress-nginx