title: "TOM.LAN"
subtitle: "Dashboard"
logo: "logo.png"

header: true
footer: false

links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/tombulled"
    target: "_blank"

services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Proxmox"
        logo: "assets/tools/sample.png"
        subtitle: "Complete open-source platform for enterprise virtualization"
        keywords: "proxmox"
        url: "https://proxmox.lan:8006/"
        target: "_blank"
      - name: "Pi-hole"
        logo: "assets/tools/sample.png"
        subtitle: "A black hole for Internet advertisements"
        keywords: "pihole"
        url: "http://pihole.lan/admin/"
        target: "_blank"
      - name: "Kasm Workspaces"
        logo: "assets/tools/sample.png"
        subtitle: "Web streaming of containerized workloads to your browser"
        keywords: "kasm"
        url: "https://kasm.lan/#/dashboard"
        target: "_blank"
      - name: "Rancher"
        logo: "assets/tools/sample.png"
        subtitle: "Complete container management platform"
        keywords: "rancher"
        url: "https://rancher.lan/dashboard/home"
        target: "_blank"