authentik:
  replicas: 1

  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/goauthentik/server
    tag: 2022.4.1

  authentik:
    error_reporting:
      enabled: false

    log_level: info

    secret_key: "Parting-Estimator-Campsite-Rotten-Galvanize-Surface"

    avatars: none

    postgresql:
      password: password

  geoip:
    enabled: false

  worker:
    replicas: 1

  ingress:
    enabled: true
    ingressClassName: ingress-nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    hosts:
      - host: authentik.k3s.lan
        paths:
          - path: /(.*)
            pathType: Prefix

  postgresql:
    enabled: true

    postgresqlPassword: password

    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 11.13.0
      pullPolicy: IfNotPresent

  redis:
    enabled: true

    image:
      registry: docker.io
      repository: bitnami/redis
      tag: 6.2.7
      pullPolicy: IfNotPresent