apiVersion: v2
name: rabbitmq
description: Helm chart for RabbitMQ (packaged by Bitnami)
type: application
version: 0.1.0
dependencies:
- name: rabbitmq
  version: 12.15.0
  repository: https://charts.bitnami.com/bitnami
