rabbitmq:
  # Common Parameters
  auth:
    username: user
    password: password

    erlangCookie: erlang-cookie

    tls:
      enabled: false

  communityPlugins: []
  extraPlugins: []

  clustering:
    enabled: false

  loadDefinition:
    enabled: false

  extraEnvVars: []
  extraConfiguration: ""
  featureFlags: ""

  ldap:
    enabled: false

  extraVolumeMounts: []
  extraVolumes: []

  # Statefulset Parameters
  replicaCount: 1
  podLabels: {}
  podAnnotations: {}
  # TODO: Use appropriate resource values
  resources:
    limits:
      memory: 1Gi
      cpu: 1
    requests:
      memory: 1Gi
      cpu: 1

  # Persistence Parameters
  persistence:
    enabled: false

  # Exposure Parameters
  ingress:
    enabled: true
    path: /
    pathType: Prefix
    hostname: rabbitmq.tom.lan
    annotations: {}
    # Note: TLS currently disabled as issuer not deployed/configured
    tls: false
    ingressClassName: ingress-nginx
  networkPolicy:
    enabled: false

  # Metrics Parameters
  metrics:
    enabled: false

  # Init Container Parameters
  volumePermissions:
    enabled: false