replicaCount: 1

ui:
  image:
    repository: tombulled/to-ui
    tag: 0.1.0
    pullPolicy: IfNotPresent

api:
  image:
    repository: tombulled/to
    tag: 0.1.0
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080