replicaCount: 1

image:
  repository: tombulled/downloader
  tag: 0.1.1-rc0
  pullPolicy: IfNotPresent

env:
  # S3
  S3_ENDPOINT: minio
  S3_ACCESS-KEY: admin
  S3_SECRET-KEY: password

  # RabbitMQ
  RABBIT_URL: amqp://user:password@rabbitmq:5672/
