{{- $releaseName := .Release.Name -}}
{{- $chartName := .Chart.Name -}}
{{- $chartVersion := .Chart.Version -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}
  labels:
    app: {{ $releaseName }}
    chart: {{ $chartName }}-{{ $chartVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $releaseName }}
  template:
    metadata:
      labels:
        app: {{ $releaseName }}
    spec:
      volumes:
      - name: config
        configMap:
          name: {{ $releaseName }}-config
      {{ range $filePath, $_ :=  .Files.Glob  "assets/images/*" }}
      {{- $fileName := base $filePath -}}
      {{- $fileId := regexReplaceAll "\\." $fileName "-" -}}
      - name: {{ printf "image-%s" $fileId }}
        configMap:
          name: {{ printf "%s-image-%s" $releaseName $fileId }}
      {{ end }}
      containers:
      - name: {{ $releaseName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: config
          mountPath: /www/assets/config.yml
          subPath: config.yml
        {{ range $filePath, $_ :=  .Files.Glob  "assets/images/*" }}
        {{- $fileName := base $filePath -}}
        {{- $fileId := regexReplaceAll "\\." $fileName "-" -}}
        - name: {{ printf "image-%s" $fileId }}
          mountPath: {{ printf "/www/assets/images/%s" $fileName }}
          subPath: {{ $fileName }}
        {{ end }}
