apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-images
  labels:
    app: {{ .Release.Name }}
binaryData:
{{ range $path, $_ :=  .Files.Glob  "assets/images/*" }}
      {{ base $path }}: {{ $.Files.Get $path | b64enc }}
{{ end }}