{{- $releaseName := .Release.Name -}}
{{- range $path, $_ :=  .Files.Glob  "assets/images/*" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{printf "%s-image-%s" $releaseName $path }}
  labels:
    app: {{ $releaseName }}
binaryData:
      {{ base $path }}: {{ $.Files.Get $path | b64enc }}
---
{{ end }}