{{- $releaseName := .Release.Name -}}
{{- range $filePath, $_ :=  .Files.Glob  "assets/images/*" -}}
{{- $fileName := base $filePath -}}
{{- $fileId := regexReplaceAll "\\." $fileName "-" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-image-%s" $releaseName $fileId }}
  labels:
    app: {{ $releaseName }}
binaryData:
      {{ $fileName }}: {{ $.Files.Get $filePath | b64enc }}
---
{{ end }}