{{ range $path, $_ :=  .Files.Glob  "assets/images/*" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-images-{{ $path }}
  labels:
    app: {{ .Release.Name }}
binaryData:
      {{ base $path }}: {{ $.Files.Get $path | b64enc }}
----
{{ end }}