step-issuer:
  replicaCount: 1

  image:
    repository: cr.step.sm/smallstep/step-issuer
    tag: 0.6.0
    pullPolicy: IfNotPresent

  deployment:
    args:
      disableApprovalCheck: true

  stepIssuer:
    create: true
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJvakNDQVVtZ0F3SUJBZ0lRUERFV1ArUGlFVnBvQXQ5dlVxWGlxakFLQmdncWhrak9QUVFEQWpBd01SSXcKRUFZRFZRUUtFd2xUYldGc2JITjBaWEF4R2pBWUJnTlZCQU1URVZOdFlXeHNjM1JsY0NCU2IyOTBJRU5CTUI0WApEVEl5TURZeE1qRXpNalF5T0ZvWERUTXlNRFl3T1RFek1qUXlPRm93TURFU01CQUdBMVVFQ2hNSlUyMWhiR3h6CmRHVndNUm93R0FZRFZRUURFeEZUYldGc2JITjBaWEFnVW05dmRDQkRRVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQk9TSVV6dy94a1FnSDkzNGZ1bDQ4UEFmcm1WK0VvNzhOckdkVFNsREtOTGxkdzNuU2F4agpPTDBNazAxcEtENmpmQ3JFVHBLM1BreGNtTXNoQVZiWDN4YWpSVEJETUE0R0ExVWREd0VCL3dRRUF3SUJCakFTCkJnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQk1CMEdBMVVkRGdRV0JCUWxsT2FaelhxL2VEQjFvYWF1bHZMeXJTNE8KbkRBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBVUJxMjdkRWxhN1hKWklUZ2lybG1sbERMckQwRlFYem8xR1FneApiNGlxYWdJZ0dma3FJK3ZMMExoZVNtcGoyZEdBK0NMZGl3UWpLWm1XYlpReVUzNkFGSW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

    provisioner:
      name: admin
      kid: IbgvwkFQkVkFE9CSMrKAPcQs-vqno9p7KFXwKozB_eo

      passwordRef:
        name: step-certificates-provisioner-password
        key: password