replicaCount: 1

image:
  repository: tombulled/homer
  tag: 22.06.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  host: homer.tom.lan
  auth: true
  tls: true


config:
  title: "TOM.LAN"
  subtitle: "Dashboard"
  logo: "logo.png"

  header: true
  footer: false

  links:
    - name: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/tombulled"
      target: "_blank"
    - name: "PyPI"
      icon: "fab fa-python"
      url: "https://pypi.org/user/tbulled/"
      target: "_blank"
    - name: "Docker Hub"
      icon: "fab fa-docker"
      url: "https://hub.docker.com/u/tombulled"
      target: "_blank"

  services:
    - name: "Applications"
      icon: "fas fa-cloud"
      items:
        - name: "Proxmox"
          logo: "assets/tools/sample.png"
          subtitle: "Open-source platform for enterprise virtualization"
          keywords: "proxmox"
          url: "https://proxmox.lan:8006/"
          target: "_blank"
        - name: "Pi-hole"
          logo: "assets/tools/sample.png"
          subtitle: "A black hole for Internet advertisements"
          keywords: "pihole"
          url: "http://pihole.lan/admin/"
          target: "_blank"
        - name: "Kasm Workspaces"
          logo: "assets/tools/sample.png"
          subtitle: "Containerized workload streaming"
          keywords: "kasm"
          url: "https://kasm.lan/#/dashboard"
          target: "_blank"
        - name: "Rancher"
          logo: "assets/tools/sample.png"
          subtitle: "Complete container management platform"
          keywords: "rancher"
          url: "https://rancher.lan/dashboard/home"
          target: "_blank"
        - name: "Argo CD"
          logo: "assets/tools/sample.png"
          subtitle: "Declarative continuous deployment for Kubernetes"
          keywords: "argo"
          url: "https://argo-cd.tom.lan/applications"
          target: "_blank"
        - name: "Gitmoji"
          logo: "assets/tools/sample.png"
          subtitle: ""
          keywords: "gitmoji"
          url: "https://gitmoji.tom.lan/"
          target: "_blank"
        - name: "HTTPBin"
          logo: "assets/tools/sample.png"
          subtitle: "HTTP Request & Response Service"
          keywords: "httpbin"
          url: "https://httpbin.tom.lan/"
          target: "_blank"
        - name: "Prometheus"
          logo: "assets/tools/sample.png"
          subtitle: "Monitoring system and time series database"
          keywords: "prometheus"
          url: "https://prometheus.tom.lan/"
          target: "_blank"
        - name: "Grafana"
          logo: "assets/tools/sample.png"
          subtitle: "Observability and data visualisation platform"
          keywords: "grafana"
          url: "https://grafana.tom.lan/"
          target: "_blank"
        - name: "Authentik"
          logo: "assets/tools/sample.png"
          subtitle: "Open-Source Identity Provider"
          keywords: "authentik"
          url: "https://authentik.tom.lan/"
          target: "_blank"
        - name: "Carbon"
          logo: "assets/tools/sample.png"
          subtitle: "Create beautiful source code images"
          keywords: "carbon"
          url: "https://carbon.tom.lan/"
          target: "_blank"
        - name: "Cyber Chef"
          logo: "assets/tools/sample.png"
          subtitle: "The Cyber Swiss Army Knife"
          keywords: "cyber-chef"
          url: "https://cyber-chef.tom.lan/"
          target: "_blank"
        - name: "Hello World"
          logo: "assets/tools/sample.png"
          subtitle: "Hello, World!"
          keywords: "hello-world"
          url: "https://hello-world.tom.lan/"
          target: "_blank"