apiVersion: v1
kind: Service
metadata:
  name: authentik-proxy-service
  labels:
    app: authentik
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: authentik