apiVersion: v1
kind: Service
metadata:
  name: authentik-proxy-service
  labels:
    app.kubernetes.io/component: server 
    app.kubernetes.io/name: authentik
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 9000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: server 
    app.kubernetes.io/name: authentik