harbor:
  # Harbor Common Parameters
  adminPassword: admin
  externalURL: "https://harbor.tom.lan"
  logLevel: info

  # Traffic Exposure Parameters
  exposureType: ingress
  ingress:
    core:
      ingressClassName: ingress-nginx
      pathType: Prefix
      hostname: harbor.tom.lan
      annotations:
        cert-manager.io/cluster-issuer: ca
      tls: true
