controller:
  image:
    registry: k8s.gcr.io
    image: ingress-nginx/controller
    tag: v1.2.0

  metrics:
    enabled: true

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  # service:
  #   type: NodePort
  #   nodePorts:
  #     http: 80
  #     https: 443