argo-cd:
  replicas: 1

  image:
    repository: quay.io/argoproj/argocd
    tag: v2.3.3
    imagePullPolicy: IfNotPresent

  controller:
    metrics:
      enabled: true

    clusterRoleRules:
      rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'

  dex:
    enabled: false

  redis:
    enabled: true

    image:
      repository: redis
      tag: 6.2.6-alpine
      imagePullPolicy: IfNotPresent

  server:
    replicas: 1

    service:
      type: ClusterIP

    metrics:
      enabled: true

    ingress:
      enabled: true
      ingressClassName: ingress-nginx
      hosts: ["argo-cd.k3s.lan"]
      paths: ["/"]
      tls:
        - secretName: argo-cd-server-tls
          hosts: ["argo-cd.k3s.lan"]
      https: true

    extraArgs:
      - --insecure

    # certificate:
    #   enabled: true
    #   domain: argo-cd.k3s.lan
    #   duration: 24h
    #   renewBefore: 8h
    #   issuer:
    #     group: certmanager.step.sm
    #     # kind: StepIssuer
    #     kind: Issuer
    #     name: step-issuer
    #   secretName: argo-cd-server-tls

  repoServer:
    replicas: 1

    metrics:
      enabled: true

  configs:
    secret:
      argocdServerAdminPassword: $2a$10$RfZBdyaoNqCqOidEUCCY6OwNIZfOaytsGzdr9Ie6NPMRhDuwSWH8y

  applicationSet:
    replicaCount: 1

    image:
      repository: quay.io/argoproj/argocd-applicationset
      tag: v0.4.1
      imagePullPolicy: IfNotPresent

    metrics:
      enabled: false

  notifications:
    enabled: false