argo-cd:
  # Global Configs
  global:
    addPrometheusAnnotations: true
    domain: argo-cd.tom.lan
    logging:
      level: info
    networkPolicy:
      create: false

  # Argo CD Configs
  configs:
    cm:
      exec.enabled: true

    secret:
      argocdServerAdminPassword: $2a$10$RfZBdyaoNqCqOidEUCCY6OwNIZfOaytsGzdr9Ie6NPMRhDuwSWH8y

  # Argo CD Controller
  controller:
    replicas: 1

    metrics:
      enabled: true

  # Argo Repo Server
  repoServer:
    replicas: 1

    metrics:
      enabled: true

  # Argo Server
  server:
    replicas: 1

    service:
      type: ClusterIP

    metrics:
      enabled: true

    ingress:
      enabled: true
      ingressClassName: ingress-nginx
      path: /
      pathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: ca
      tls: true
      extraTls:
        - secretName: argo-cd.tom.lan-tls
          hosts:
            - argo-cd.tom.lan

    extraArgs:
      - --insecure

    extensions:
      enabled: true

    extensionList: []

  # Dex
  dex:
    enabled: false

  # Redis
  redis:
    enabled: true

  # ApplicationSet
  applicationSet:
    replicaCount: 1

    metrics:
      enabled: true

  # Notifications
  notifications:
    enabled: false
