minio:
  # MinIO Parameters
  auth:
    rootUser: admin
    rootPassword: password

  defaultBuckets: bucket-a,bucket-b

  # Traffic Exposure Parameters
  ingress:
    enabled: true
    ingressClassName: ingress-nginx
    hostname: minio-console.tom.lan
    path: /
    pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: ca
      # Fix for "413 Request Entity Too Large"
      nginx.ingress.kubernetes.io/proxy-body-size: 0
    tls: true
  apiIngress:
    enabled: true
    ingressClassName: ingress-nginx
    hostname: minio.tom.lan
    path: /
    pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: ca
      # Fix for "413 Request Entity Too Large"
      nginx.ingress.kubernetes.io/proxy-body-size: 0
    tls: true
  networkPolicy:
    enabled: false

  # Persistence Parameters
  persistence:
    enabled: false

  # Volume Permission Parameters
  volumePermissions:
    enabled: false
