minio:
  # MinIO Parameters
  image:
    repository: bitnami/minio

  clientImage:
    repository: bitnami/minio-client

  mode: standalone

  auth:
    rootUser: admin
    rootPassword: password

  defaultBuckets: bucket-a,bucket-b

  # MinIO Deployment/StatefulSet Parameters
  containerPorts:
    api: 9000
    console: 9001

  podLabels: {}
  podAnnotations: {}

  # Traffic Exposure Parameters
  service:
    type: ClusterIP
    ports:
      api: 9000
      console: 9001
  ingress:
    enabled: true
    ingressClassName: ingress-nginx
    hostname: minio-console.tom.lan
    path: /
    pathType: Prefix
    annotations:
      cert-manager.io/issuer: step-issuer
      cert-manager.io/issuer-kind: StepClusterIssuer
      cert-manager.io/issuer-group: certmanager.step.sm
    tls: true
  apiIngress:
    enabled: true
    ingressClassName: ingress-nginx
    hostname: minio.tom.lan
    path: /
    pathType: Prefix
    annotations:
      cert-manager.io/issuer: step-issuer
      cert-manager.io/issuer-kind: StepClusterIssuer
      cert-manager.io/issuer-group: certmanager.step.sm
    tls: true
  networkPolicy:
    enabled: false

  # Persistence Parameters
  persistence:
    enabled: false

  # Volume Permission Parameters
  volumePermissions:
    enabled: false
