apiVersion: v2
name: step-certificates
description: Helm chart for [Step Certificates](https://github.com/smallstep/certificates)
type: application
version: 0.1.0
appVersion: 0.18.1
dependencies:
- name: step-certificates
  version: 1.18.2+20220324